services:
    # PHP-FPM контейнер
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - laravel_network

    # Nginx контейнер
    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        extra_hosts:
                    - "laravel:127.0.0.1"
        depends_on:
            - app
        networks:
            - laravel_network

    # PostgreSQL контейнер
    db:
        image: postgres:15
        container_name: laravel_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - laravel_network
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        networks:
            - laravel_network

# Тома для хранения данных
volumes:
    postgres_data:

# Сети для связи контейнеров
networks:
    laravel_network:
        driver: bridge
